### ISSUE TITLE
Failed to set up: Check the logs

### ISSUE THREAD

**Issue by feddiriko** [grotteru/home_assistant_norwegian_namedays#1]
Thank you for this integration. After upgrading to 2025.5.0b0 this integration stopped working. 

Please see log below. 

`Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 2:25:35 PM (2 occurrences)
Last logged: 3:24:35 PM

Error setting up entry Norwegian Namedays for norwegian_namedays
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/norwegian_namedays/__init__.py", line 11, in async_setup_entry
    session = hass.helpers.aiohttp_client.async_get_clientsession()
              ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'`

I made a fix in my fork. https://github.com/feddiriko/home_assistant_norwegian_namedays/blob/main/custom_components/norwegian_namedays/__init__.py

**Comment by grotteru** [comment]
Hi. Thanks for the contribution. It did not fail on my instance but your solution is good.

This integration was my first ever. I should make a better Readme also. 

I think I managed to merge your PR now.
